### ISSUE TITLE
Why Gates calcultion are incorrect?

### ISSUE THREAD

**Issue by Divinely5782** [CReizner/SharpAstrology.HumanDesign#1]
Hi! First of kindly appreciate for sharing a great project! 

I have tried to calculate a chart: **Local:** 14.01.2024 12:00 (Washington (Washington, D.C.),United States) **in UTC**: 17:00
and there was everything correct except Gates number. I have created a temporary web version of your library available by this link: 
http://31.129.42.210:8080/astrology?dateOfBirth=2024-01-14T17:00:02Z

I have calculated chart using official website and here is the result:
![2024-01-14_22-37-12](https://github.com/CReizner/SharpAstrology.HumanDesign/assets/129745558/36eb38c3-d7a5-4e85-a855-8c2244ed3b6e)

Can you please help? Thanks!

**Comment by CReizner** [comment]
Hi @Divinely5782 
Did you use the SwissEph package with JPL files or swiss eph files? Because there can be a  accuracy problem with the mosier semianalytic approach.

**Comment by CReizner** [comment]
@Divinely5782 
I've checked your datetime with the swiss eph files based calculation and I got a result in alignment with the online calculator:
Personality:
        Sun Key61-Four
        Earth Key62-Four
        Mars Key58-Four
        Mercury Key10-Three
        Venus Key26-Three
        Moon Key37-Three
        Jupiter Key27-Five
        Saturn Key55-Five
        Uranus Key23-One
        Neptune Key36-Three
        Pluto Key60-Four
        NorthNode Key51-Five
        SouthNode Key57-Five

Design:
        Sun Key32-Six
        Earth Key42-Six
        Mars Key28-Four
        Mercury Key32-Six
        Venus Key40-Five
        Moon Key11-Two
        Jupiter Key24-Six
        Saturn Key55-One
        Uranus Key23-Four
        Neptune Key36-Three
        Pluto Key60-Two
        NorthNode Key42-Five
        SouthNode Key32-Five

**Comment by CReizner** [comment]
I've updated the README with a hint to use JPL or swiss eph files for exact calculations.
Thank you!
