### ISSUE TITLE
Feature Request: Add Conscious and Unconscious Centers

### ISSUE THREAD

**Issue by pelim** [CReizner/SharpAstrology.HumanDesign#3]
Request to add ConsciousCenters and UnconsciousCenters properties to the SharpAstrology.HumanDesign library. These properties are crucial for comprehensive Human Design chart analysis.

**Comment by CReizner** [comment]
Hi @pelim. Do you mean the open and defined centers? Or do you mean, if a center is activated only by unconscious or only by conscious channels?

**Comment by CReizner** [comment]
The requested feature was added in version 1.1.0.
