### ISSUE TITLE
Feature request: Light and Shadow Aspects

### ISSUE THREAD

**Issue by offline-first** [CReizner/SharpAstrology.HumanDesign#5]
Can you calculate for the gates, the light and shadow aspects which are next to the planets in the chart as triangle upwards (light), triangle downwards shadow, star (if both aspects are extremely lived out)? Unfortunately, I can't find any information on how these are determined. ..

**Comment by CReizner** [comment]
Hello @offline-first,
thanks for your question.

You actually have properties available in all three HumanDesign Charts to get this information.
Search the charts for properties with Fixation in their names. There you will find a **Dictionary<Planets, PlanetaryFixation>** of which planet produces which fixation. In PlanetaryFixation.FixingState you will find the states you are looking for as Exalted (up), Detriment (down) and Juxtaposed (star).

**Comment by CReizner** [comment]
Code example:
using SharpAstrology.DataModels;
using SharpAstrology.Enums;
using SharpAstrology.Ephemerides;
using SharpAstrology.Interfaces;

var date = new DateTime(1988, 9, 4, 1, 15, 0, DateTimeKind.Utc);

var ephemeridesService = new SwissEphemeridesService(ephType: EphType.Moshier);
using IEphemerides eph = ephemeridesService.CreateContext();

// Create chart
var chart = new HumanDesignChart(date, eph);

// Personality planets
foreach (var (planet, activation) in chart.PersonalityActivation)
{
    Console.WriteLine($"{planet} - {activation.Gate}/{activation.Line} {chart.PersonalityFixation[planet].FixingState}");
}
// Output:
// Sun - Key64/One None
// Earth - Key63/One None
// Mars - Key21/Two Exalted
// Mercury - Key18/Three Exalted
// Venus - Key56/One None
// Moon - Key45/Six None
// Jupiter - Key20/Six None
// Saturn - Key11/Four None
// Uranus - Key11/Five None
// Neptune - Key58/Four Detriment
// Pluto - Key44/Three None
// NorthNode - Key63/Three None
// SouthNode - Key64/Three None

// Design planets
foreach (var (planet, activation) in chart.DesignActivation)
{
    Console.WriteLine($"{planet} - {activation.Gate.ToNumber()}/{activation.Line.ToNumber()} {chart.DesignFixation[planet].FixingState}");
}
// Output:
// Sun - 35/3 Detriment
// Earth - 5/3 None
// Mars - 37/3 Detriment
// Mercury - 12/5 None
// Venus - 12/5 None
// Moon - 41/1 None
// Jupiter - 23/2 Exalted
// Saturn - 10/3 None
// Uranus - 10/2 None
// Neptune - 58/6 Detriment
// Pluto - 44/3 None
// NorthNode - 22/2 None
// SouthNode - 47/3 None

**Comment by offline-first** [comment]
Thank you very much for your help! I'm seriously wondering how you found all this out! I spent hours researching...
